-- Generated by gcb. DO NOT EDIT.
return {
  [1001] = {
    id = 1001,
    name = "铁剑",
    quality = 0,
    price = 0,
    rewards = {

    },
    attrs = {
      ["攻击"] = 5.5,
    },
    craftFrom = 2001,
  },
  [1002] = {
    id = 1002,
    name = "铁盾",
    quality = 1,
    price = 120,
    rewards = {
      {
        itemId = 1001,
        count = 2,
      },
    },
    attrs = {

    },
    craftFrom = 2002,
  },
  [1003] = {
    id = 1003,
    name = "草药",
    quality = 0,
    price = 10,
    rewards = {

    },
    attrs = {

    },
    craftFrom = 2003,
  },
}
