-- Generated by gcb. DO NOT EDIT.
return {
  [2001] = {
    id = 2001,
    name = "铁矿石",
    tier = 1,
  },
  [2002] = {
    id = 2002,
    name = "皮革",
    tier = 2,
  },
  [2003] = {
    id = 2003,
    name = "草药种子",
    tier = 1,
  },
}
