-- Generated by gcb. DO NOT EDIT.
return {
  ["ui.settings"] = {
    key = "ui.settings",
    zh = "设置",
    en = "Settings",
  },
  ["ui.start"] = {
    key = "ui.start",
    zh = "开始游戏",
    en = "Start",
  },
}
