// Lua target（docs/04 §8.3）：每表一个 return 模块文件；缩进 2 空格；末尾保留逗号。
// 顶层键 = 主键：int 用 [1001]，string 用 ["abc"]；enum → int；字符串转义 \ " \n \t。

import { parseTypeString } from '@gcb/schema';
import type { FieldDef, SchemaIr, TableDef, TypeAst } from '@gcb/schema';
import type { Row, RowValue, TypedRow } from '@gcb/validate';
import type { ExportContext, OutputFile, TargetPlugin } from './plugin.js';

function escapeLuaString(s: string): string {
  let out = '"';
  for (const ch of s) {
    if (ch === '\\') out += '\\\\';
    else if (ch === '"') out += '\\"';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\t') out += '\\t';
    else out += ch;
  }
  return out + '"';
}

function luaFloat(value: number): string {
  const v = value === 0 ? 0 : value;
  const s = String(v);
  return /[.e]/.test(s) ? s : s + '.0';
}

function luaValue(value: RowValue, ast: TypeAst, ir: SchemaIr, indent: string): string {
  const inner = indent + '  ';
  switch (ast.kind) {
    case 'primitive':
      if (ast.name === 'bool') return value ? 'true' : 'false';
      if (ast.name === 'int') return String(value);
      if (ast.name === 'float') return luaFloat(value as number);
      return escapeLuaString(value as string);
    case 'enum': {
      const enumDef = ir.enums[ast.enumName];
      if (enumDef === undefined || typeof value !== 'string') return 'nil';
      const member = enumDef.values.find((v) => v.name === value);
      return member ? String(member.value) : 'nil';
    }
    case 'ref':
      return typeof value === 'number' ? String(value) : escapeLuaString(value as string);
    case 'struct': {
      const structDef = ir.structs[ast.structName];
      if (structDef === undefined) return '{}';
      return luaFields(value as Row, structDef.fields, ir, indent);
    }
    case 'list': {
      const items = (value as RowValue[]).map(
        (v) => `${inner}${luaValue(v, ast.element, ir, inner)},`,
      );
      return `{\n${items.join('\n')}\n${indent}}`;
    }
    case 'map': {
      const entries = [...(value as Map<string | number, RowValue>).entries()];
      entries.sort((a, b) => {
        if (a[0] === b[0]) return 0;
        return ast.key === 'int' ? Number(a[0]) - Number(b[0]) : a[0] < b[0] ? -1 : 1;
      });
      const items = entries.map(([k, v]) => {
        const keyText = ast.key === 'int' ? String(k) : escapeLuaString(String(k));
        return `${inner}[${keyText}] = ${luaValue(v, ast.element, ir, inner)},`;
      });
      return `{\n${items.join('\n')}\n${indent}}`;
    }
    case 'union': {
      const unionDef = ir.unions[ast.unionName];
      const obj = value as Record<string, RowValue>;
      if (unionDef === undefined) return '{}';
      const variantName = obj[unionDef.tag];
      const variant =
        typeof variantName === 'string'
          ? unionDef.variants.find((v) => v.name === variantName)
          : undefined;
      const variantStruct = variant ? ir.structs[variant.struct] : undefined;
      const innerFields: string[] = [];
      if (variantStruct !== undefined) {
        const structValue = obj['value'] as Row;
        for (const field of variantStruct.fields) {
          const ast2 = parseTypeString(field.type);
          if (!ast2.ok) continue;
          const v = luaValue(structValue[field.name] as RowValue, ast2.ast, ir, inner);
          innerFields.push(`${inner}${field.name} = ${v},`);
        }
      }
      return `{\n${inner}${unionDef.tag} = ${escapeLuaString(String(variantName))},\n${inner}value = {\n${innerFields.join('\n')}\n${inner}},\n${indent}}`;
    }
  }
}

function luaFields(value: Row, fields: FieldDef[], ir: SchemaIr, indent: string): string {
  const inner = indent + '  ';
  const lines: string[] = [];
  for (const field of fields) {
    const ast2 = parseTypeString(field.type);
    if (!ast2.ok) continue;
    const v = luaValue(value[field.name] as RowValue, ast2.ast, ir, inner);
    lines.push(`${inner}${field.name} = ${v},`);
  }
  return `{\n${lines.join('\n')}\n${indent}}`;
}

function luaTable(table: TableDef, rows: TypedRow[], ir: SchemaIr): string {
  const lines: string[] = ['-- Generated by gcb. DO NOT EDIT.', 'return {'];
  for (const row of rows) {
    const key = /^-?\d+$/.test(row.pk) ? `[${row.pk}]` : `[${JSON.stringify(row.pk)}]`;
    lines.push(`  ${key} = ${luaFields(row.row, table.fields, ir, '  ')},`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

export const luaTarget: TargetPlugin = {
  name: 'lua',
  generate(ctx: ExportContext): OutputFile[] {
    const files: OutputFile[] = [];
    for (const tableName of Object.keys(ctx.ir.tables).sort()) {
      const table = ctx.ir.tables[tableName];
      if (table === undefined) continue;
      const rows = ctx.tables.get(tableName) ?? [];
      files.push({ path: `lua/${tableName}.lua`, content: luaTable(table, rows, ctx.ir) });
    }
    return files;
  },
};
