// Generated by gcb. DO NOT EDIT.
using System;
using System.Collections.Generic;
namespace GameConfig;

public sealed class Hero {
  public int Id { get; set; }
  public string Name { get; set; }
  public int Level { get; set; }
  public ItemQuality Quality { get; set; }
  public Dictionary<int, int> Equipment { get; set; }
  public List<int> SkillIds { get; set; }
}
