// Generated by gcb. DO NOT EDIT.
using System;
using System.Collections.Generic;
namespace GameConfig;

public sealed class Item {
  public int Id { get; set; }
  public string Name { get; set; }
  public ItemQuality Quality { get; set; }
  public int Price { get; set; }
  public List<RewardItem> Rewards { get; set; }
  public Dictionary<string, float> Attrs { get; set; }
  public int CraftFrom { get; set; }
}
