// Generated by gcb. DO NOT EDIT.
using System;
namespace GameConfig;

public sealed class Material {
  public int Id { get; set; }
  public string Name { get; set; }
  public int Tier { get; set; }
}
