// Generated by gcb. DO NOT EDIT.
using System;
using System.Collections.Generic;
namespace GameConfig;

public sealed class Skill {
  public int Id { get; set; }
  public string Name { get; set; }
  public SkillEffect OnUse { get; set; }
  public List<string> Tags { get; set; }
}
