// Generated by gcb. DO NOT EDIT.
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace GameConfig;

public enum SkillEffectTag {
  Damage,
  Heal,
}

public abstract class SkillEffect {
  public abstract SkillEffectTag Tag { get; }
}

public sealed class SkillEffectDamage : SkillEffect {
  public override SkillEffectTag Tag => SkillEffectTag.Damage;
  public DamageParams Value { get; set; } = new DamageParams();
}

public sealed class SkillEffectHeal : SkillEffect {
  public override SkillEffectTag Tag => SkillEffectTag.Heal;
  public HealParams Value { get; set; } = new HealParams();
}
