// Generated by gcb. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace GameConfig;

public sealed class ConfigException : Exception {
  public ConfigException(string message) : base(message) {}
}

public sealed class TableFile<TRow> {
  public string Table { get; set; } = "";
  public string PrimaryKey { get; set; } = "";
  public List<TRow> Rows { get; set; } = new();
}

public static class TablesLoader {
  public static Tables Load(string jsonDir) {
    var options = new JsonSerializerOptions();
    options.Converters.Add(new SkillEffectConverter());
    var tables = new Tables();
    tables.Hero = LoadIndex<Hero, int>(Path.Combine(jsonDir, "Hero.json"), r => r.Id, options);
    tables.Item = LoadIndex<Item, int>(Path.Combine(jsonDir, "Item.json"), r => r.Id, options);
    tables.Material = LoadIndex<Material, int>(Path.Combine(jsonDir, "Material.json"), r => r.Id, options);
    tables.Skill = LoadIndex<Skill, int>(Path.Combine(jsonDir, "Skill.json"), r => r.Id, options);
    tables.Text = LoadIndex<Text, string>(Path.Combine(jsonDir, "Text.json"), r => r.Key, options);
    return tables;
  }

  private static TableIndex<TRow, TPk> LoadIndex<TRow, TPk>(string path, Func<TRow, TPk> keyOf, JsonSerializerOptions options) {
    var json = File.ReadAllText(path);
    var file = JsonSerializer.Deserialize<TableFile<TRow>>(json, options);
    if (file == null) throw new ConfigException($"表文件为空：{path}");
    var byPk = new Dictionary<TPk, TRow>();
    foreach (var row in file.Rows) {
      var k = keyOf(row);
      if (!byPk.TryAdd(k, row)) throw new ConfigException($"主键重复：{path} #{k}");
    }
    return new TableIndex<TRow, TPk> { Rows = file.Rows, ByPk = byPk };
  }
}

public sealed class SkillEffectConverter : JsonConverter<SkillEffect> {
  public override SkillEffect Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) {
    using var doc = JsonDocument.ParseValue(ref reader);
    var element = doc.RootElement;
    var tag = element.GetProperty("effectType").GetString();
    switch (tag) {
      case "Damage": return new SkillEffectDamage { Value = element.GetProperty("value").Deserialize<DamageParams>(options) ?? throw new ConfigException("变体数据为空") };
      case "Heal": return new SkillEffectHeal { Value = element.GetProperty("value").Deserialize<HealParams>(options) ?? throw new ConfigException("变体数据为空") };
      default: throw new ConfigException($"未知变体：{tag}");
    }
  }
  public override void Write(Utf8JsonWriter writer, SkillEffect value, JsonSerializerOptions options) => throw new NotSupportedException();
}
