// Generated by gcb. DO NOT EDIT.
using System;
using System.Collections.Generic;
namespace GameConfig;

public sealed class Tables {
  public TableIndex<Hero, int> Hero { get; init; } = default!;
  public TableIndex<Item, int> Item { get; init; } = default!;
  public TableIndex<Material, int> Material { get; init; } = default!;
  public TableIndex<Skill, int> Skill { get; init; } = default!;
  public TableIndex<Text, string> Text { get; init; } = default!;
}

public sealed class TableIndex<TRow, TPk> {
  public required IReadOnlyList<TRow> Rows { get; init; }
  public required IReadOnlyDictionary<TPk, TRow> ByPk { get; init; }
  public TRow Get(TPk pk) => ByPk[pk];
}
