// Generated by gcb. DO NOT EDIT.
using System;
namespace GameConfig;

public sealed class Text {
  public string Key { get; set; }
  public string Zh { get; set; }
  public string En { get; set; }
}
